
spring:
  application:
    name: "eurekaserver"
# H2 configurations end here --
  config:
    import: "optional:configserver:http://localhost:8071/"
        
 # Enable all endpoints of actuator - we will consume the refresh endpoint to refresh configurations at runtime
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true  
  metrics: #required by micrometer. this tells micrometer & prometheus to group all metrics of this microservices under application name = $(spring.application.name). 
    tags:
      application: $(spring.application.name)    
      
logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"              
        