server:
  port: 8090
spring:
  application:
    name: "loans"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
  jpa:
    show-sql: true #to show the fired sql statements in concole window
  sql:
    init:
      mode: always #always run the schema.sql
  config:
    import: "optional:configserver:http://localhost:8071/"

# settings to expose all actuator endpoints - to implement auto-refresh capability    
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
