    
build:
  version: "3.0"

accounts:
  message: "Welcome to FFC accounts related local APIs "
  contactDetails:
    name: "Sanjeev Tiwari - Developer - accounts microservice"
    email: "sanjeev.t@futuraforge.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
    