
build:
  version: "1.0"

accounts:
  message: "Welcome to FFC bank accounts related prod APIs "
  contactDetails:
    name: "Sarita - Product Owner - accounts"
    email: "Sarita@futuraforge.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384