
build:
  version: "1.0"

accounts:
  message: "Welcome to FFC bank loans related prod APIs "
  contactDetails:
    name: "Sarita Tiwari - Product Owner- loans"
    email: "sarita@futuraforge.com"
  onCallSupport:
  - (453) 392-4829
  - (236) 203-0384