    
build:
  version: "3.0"

accounts:
  message: "Welcome to FFC accounts related local APIs "
  contactDetails:
    name: "Anisha Tiwari - Developer - loans mrcroservice"
    email: "anisha@futuraforge.com"
  onCallSupport:
  - (555) 555-1234
  - (555) 523-1345
    